version: "3.9"

services:
  mips_app:
    container_name: "mips_app"
    build: 
      context: "./" # folder
      dockerfile: "dockerfile"
    volumes:
      - "./logs:/var/lib/mips_app/data"

volumes:
  mips_data: