mips:
  rps_config:
    method:
      get:
        rps: 10
      put:
        rps: 5
      post:
        rps: 5
  rps_config_parsing_mode: "method"
  timeout: 10
  base_url: "http://10.38.0.2:9000/MIPS/"

secrets_yaml: "secrets/secrets.yaml"

telegram:
  chat_id: -4221334555
  log_chat_id: -4221334555
  timeout: 10
  user_to_tag: 335963598
  rps_config:
    rps: 1
  rps_config_parsing_mode: "blanket"

google_sheets:
  spreadsheet: "1kCZMA8c3uvFzakMv1D4BF19FKzlpOPdufTsvZUUSe7o"
  tabs:
    control_panel:
      name: "control_panel"
      schema:
        workflow:
          sheet_name: "workflow"
          type: "Utf8"
        hours_to_run:
          sheet_name: "hours_to_run"
          type: "Utf8"
        toggle:
          sheet_name: "toggle"
          type: "Utf8"
        mode:
          sheet_name: "mode"
          type: "Utf8"
        arguments:
          sheet_name: "arguments"
          type: "Utf8"
        
    execute_logs:
      name: "execute_logs"
      row_limit: 20000
      schema:
        workflow:
          sheet_name: "workflow"
          type: "Utf8"
        start_ts:
          sheet_name: "start_ts"
          type: "Utf8"
        end_ts:
          sheet_name: "end_ts"
          type: "Utf8"
        error:
          sheet_name: "error"
          type: "Utf8"
        mode:
          sheet_name: "mode"
          type: "Utf8"
          
    patch_backlight_logs:
      name: "patch_backlight_logs"
      row_limit: 20000
      schema:
        device:
          sheet_name: "device"
          type: "Int32"
        start_ts:
          sheet_name: "start_ts"
          type: "Utf8"
        end_ts:
          sheet_name: "end_ts"
          type: "Utf8"
        backlight_status:
          sheet_name: "backlight_status"
          type: "Utf8"
        error:
          sheet_name: "error"
          type: "Utf8"
        mode:
          sheet_name: "mode"
          type: "Utf8"
  token: "secrets/sheets.json"
  read_rps: 1
  write_rps: 1
  request_timeout: 30
